version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo_root_password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    secrets:
      - mongo_root_password

  api:
    build:
      context: .
      dockerfile: TickerSubscription/Dockerfile
    container_name: api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TickerStoreSettings__ConnectionString: mongodb://root:${MONGO_ROOT_PASSWORD}@mongo:27017/tickerDb?authSource=admin
    ports:
      - "5000:80"
    depends_on:
      - mongo

volumes:
  mongo-data:

secrets:
  mongo_root_password:
    file: .env
